### ISSUE TITLE
求https://www.bilibili.com/video/BV1Tr4y177LG中的源码

### ISSUE THREAD

**Issue by BlanKpaper3884** [SorenEricMent/OpenXueHai#6]
如题,
尤其是云作业催交api这段,
如果不方便，可以发至邮箱IamZBK@163.com,
还有就是哪位大神能发一下设置里其他模块的com名称(像视频中的com.samsung.accessibility)(尤其是设备管理器)
谢谢

**Comment by DF768** [comment]
这个bug已经被修复
