### ISSUE TITLE
关于root的问题（p200）

### ISSUE THREAD

**Issue by Hwenray** [SorenEricMent/OpenXueHai#8]
请问有无需清数据的root方案吗？
目前已破解（卡bug出去而已）

**Comment by butlanys** [comment]
> 请问有无需清数据的root方案吗？ 目前已破解（卡bug出去而已）

没有，解BL会清除数据，但是我的主页有最新安装包，卸载了可以装回去。

**Comment by butlanys** [comment]
root以后建议使用应用伪装，然后用爱玩机工具箱打开后台调试页把设备管控和日志上报关掉。

**Comment by butlanys** [comment]
建议别乱登教师账号，我在广东清远登了江苏老师的教师账号被抓了，被抓前的一天我发现学海的后台协助一直显示协助中，你可以拿这个作为参考（被抓前赶紧删第三方应用，我平板被没收的时候来不及清除数据，平板连着sd卡被收了，数据全被看光了）

**Comment by 111inhistory** [comment]
有个通用破解方法：扭头看电脑大法
是0408版本卸载掉了吗？（小平板）

**Comment by butlanys** [comment]
> 有个通用破解方法：扭头看电脑大法 是0408版本卸载掉了吗？（小平板）

我现在用的备用机，备用机基本废了，啥也搞不了，还贼卡

**Comment by Hwenray** [comment]
那xh老师会删你SD卡的文件吗？

**Comment by Hwenray** [comment]
我现在直接暂停智通平台，冻结智通云，貌似不会被发现，也不会要你重新登陆(内鬼确实多)

**Comment by HWR20080716** [comment]
嘿，我也是清远呢，不会同校把。。。

**Comment by Hwenray** [comment]
> 建议别乱登教师账号，我在广东清远登了江苏老师的教师账号被抓了，被抓前的一天我发现学海的后台协助一直显示协助中，你可以拿这个作为参考（被抓前赶紧删第三方应用，我平板被没收的时候来不及清除数据，平板连着sd卡被收了，数据全被看光了）

你没设置🔒屏密码吗？我的话估计被抓只能重新被刷机，貌似还要花600元把knox飞线接回来(因为学海没knox api/root权限就什么也不是)

**Comment by butlanys** [comment]
> > 建议别乱登教师账号，我在广东清远登了江苏老师的教师账号被抓了，被抓前的一天我发现学海的后台协助一直显示协助中，你可以拿这个作为参考（被抓前赶紧删第三方应用，我平板被没收的时候来不及清除数据，平板连着sd卡被收了，数据全被看光了）
> 
> 你没设置🔒屏密码吗？我的话估计被抓只能重新被刷机，貌似还要花600元把knox飞线接回来(因为学海没knox api/root权限就什么也不是)

不不不，学海定制的平板BL锁随便解，上锁再走一遍解锁流程就行，这台平板的knox根本熔不断

**Comment by butlanys** [comment]
> 嘿，我也是清远呢，不会同校把。。。

我特么认识你

**Comment by HWR20080716** [comment]
你是huangqiyu是吧

**Comment by butlanys** [comment]
> 你是huangqiyu是吧

嗯，劝删！

**Comment by butlanys** [comment]
新版智通平台和智通云已发布
智通云：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E4%BA%91_v1.9.89.20230503S
智通平台：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E5%B9%B3%E5%8F%B0v3.93.16.20230505S

**Comment by HWR20080716** [comment]
你又双叒叕出去了？

**Comment by Hwenray** [comment]
> 新版智通平台和智通云已发布
> 智通云：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E4%BA%91_v1.9.89.20230503S
> 智通平台：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E5%B9%B3%E5%8F%B0v3.93.16.20230505S

你又双叒叕出去力？

**Comment by butlanys** [comment]
> > 新版智通平台和智通云已发布
> > 智通云：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E4%BA%91_v1.9.89.20230503S
> > 智通平台：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E5%B9%B3%E5%8F%B0v3.93.16.20230505S
> 
> 你又双叒叕出去力？

咋可能，备用机啥都有mdm锁。

**Comment by Hwenray** [comment]
> > > 新版智通平台和智通云已发布
> > > 智通云：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E4%BA%91_v1.9.89.20230503S
> > > 智通平台：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E5%B9%B3%E5%8F%B0v3.93.16.20230505S
> > 
> > 你又双叒叕出去力？
> 
> 咋可能，备用机啥都有mdm锁。

太难了😫😫😫

**Comment by DF768** [comment]
> > > 新版智通平台和智通云已发布
> > > 智通云：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E4%BA%91_v1.9.89.20230503S
> > > 智通平台：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E5%B9%B3%E5%8F%B0v3.93.16.20230505S
> > 
> > 你又双叒叕出去力？
> 
> 咋可能，备用机啥都有mdm锁。

ps：备用机可以直接破解（

**Comment by DF768** [comment]
> > > > 新版智通平台和智通云已发布
> > > > 智通云：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E4%BA%91_v1.9.89.20230503S
> > > > 智通平台：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E5%B9%B3%E5%8F%B0v3.93.16.20230505S
> > > 
> > > 你又双叒叕出去力？
> > 
> > 咋可能，备用机啥都有mdm锁。
> 
> ps：备用机可以直接破解（

虽然我不知道具体步骤

**Comment by butlanys** [comment]
> > > > 新版智通平台和智通云已发布
> > > > 智通云：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E4%BA%91_v1.9.89.20230503S
> > > > 智通平台：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E5%B9%B3%E5%8F%B0v3.93.16.20230505S
> > > 
> > > 你又双叒叕出去力？
> > 
> > 咋可能，备用机啥都有mdm锁。
> 
> ps：备用机可以直接破解（

该试的都试了，要么mdm锁，禁用，精简，冻结

**Comment by Hwenray** [comment]
> > > > > 新版智通平台和智通云已发布
> > > > > 智通云：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E4%BA%91_v1.9.89.20230503S
> > > > > 智通平台：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E5%B9%B3%E5%8F%B0v3.93.16.20230505S
> > > > 
> > > > 你又双叒叕出去力？
> > > 
> > > 咋可能，备用机啥都有mdm锁。
> > 
> > ps：备用机可以直接破解（
> 
> 该试的都试了，要么mdm锁，禁用，精简，冻结

你不try下？虽然pj了也卡的一批，看个洋葱都卡

**Comment by butlanys** [comment]
> > > > > > 新版智通平台和智通云已发布
> > > > > > 智通云：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E4%BA%91_v1.9.89.20230503S
> > > > > > 智通平台：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E5%B9%B3%E5%8F%B0v3.93.16.20230505S
> > > > > 
> > > > > 你又双叒叕出去力？
> > > > 
> > > > 咋可能，备用机啥都有mdm锁。
> > > 
> > > ps：备用机可以直接破解（
> > 
> > 该试的都试了，要么mdm锁，禁用，精简，冻结
> 
> 你不try下？虽然pj了也卡的一批，看个洋葱都卡

洋葱一开倍速就卡成shi，对他期望不大，我想搞我同桌的pad

**Comment by Hwenray** [comment]
> > > > > > > 新版智通平台和智通云已发布
> > > > > > > 智通云：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E4%BA%91_v1.9.89.20230503S
> > > > > > > 智通平台：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E5%B9%B3%E5%8F%B0v3.93.16.20230505S
> > > > > > 
> > > > > > 你又双叒叕出去力？
> > > > > 
> > > > > 咋可能，备用机啥都有mdm锁。
> > > > 
> > > > ps：备用机可以直接破解（
> > > 
> > > 该试的都试了，要么mdm锁，禁用，精简，冻结
> > 
> > 你不try下？虽然pj了也卡的一批，看个洋葱都卡
> 
> 洋葱一开倍速就卡成shi，对他期望不大，我想搞我同桌的pad

oh
我认为备用机很多都是上一届淘汰之类的
