### ISSUE TITLE
新版智通平台和智通云已发布

### ISSUE THREAD

**Issue by butlanys** [SorenEricMent/OpenXueHai#9]
智通云：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E4%BA%91_v1.9.89.20230503S
智通平台：https://github.com/HQY-admin/openxuehai/releases/tag/%E6%99%BA%E9%80%9A%E5%B9%B3%E5%8F%B0v3.93.16.20230505S

**Comment by Hwenray** [comment]
我也搞了个https://github.com/HWR20080716/UnhideXueHai/releases/tag/xuehai

**Comment by butlanys** [comment]
> 我也搞了个https://github.com/HWR20080716/UnhideXueHai/releases/tag/xuehai

我没死之前收集了一大堆xhAPP

**Comment by Hwenray** [comment]
> > 我也搞了个https://github.com/HWR20080716/UnhideXueHai/releases/tag/xuehai
> 
> 我没死之前收集了一大堆xhAPP

nb

**Comment by ZRYZJ** [comment]
我平板屏幕坏了，由于维修要700，太贵了，我就花260买了个新的。
在把平板交给学海老师前，我在平板上创建了一个新用户。然后学海老师就把智通云装在了新用户里。。。
于是我就实现了智通云和正常系统共存。。。
“所有者”用户可以使用正常系统。

**Comment by ZRYZJ** [comment]
我甚至想反编译apk,结果失败了

**Comment by butlanys** [comment]
> 我甚至想反编译apk,结果失败了

别想，一堆加密加固搞到你哭

**Comment by butlanys** [comment]
> 我平板屏幕坏了，由于维修要700，太贵了，我就花260买了个新的。
> 在把平板交给学海老师前，我在平板上创建了一个新用户。然后学海老师就把智通云装在了新用户里。。。
> 于是我就实现了智通云和正常系统共存。。。
> “所有者”用户可以使用正常系统。

学海老师都不看的吗？

**Comment by ZRYZJ** [comment]
学海老师说她不会装，让别人帮她弄的。

谢谢你的APK，不然我卸载掉学海后就没法装回去了。

**Comment by butlanys** [comment]
> 学海老师说她不会装，让别人帮她弄的。
> 
> 谢谢你的APK，不然我卸载掉学海后就没法装回去了。
> 

为什么？

**Comment by Hwenray** [comment]
> 我平板屏幕坏了，由于维修要700，太贵了，我就花260买了个新的。 在把平板交给学海老师前，我在平板上创建了一个新用户。然后学海老师就把智通云装在了新用户里。。。 于是我就实现了智通云和正常系统共存。。。 “所有者”用户可以使用正常系统。

你们xh老师真6

**Comment by BuckyHYC** [comment]
现在最新版的P615c还有可靠方法共存吗？
似乎最新的更新把大多数功能都禁用了emm

**Comment by Jerry-Gren** [comment]
> > > 我也搞了个https://github.com/HWR20080716/UnhideXueHai/releases/tag/xuehai
> > 
> > 
> > 我没死之前收集了一大堆xhAPP
> 
> nb

我也备份了一些，有非常远古的版本（标old的），还有两个测试版本的智通平台（标test的），现在应该还是可用的（禁用自动更新即可）：

https://github.com/Jerry-Gren/Test-XH/releases/tag/v0.1.0

这里面test_com.xh.zhitongyunstu_v3.74.5.20220624S和com.xuehai.launcher_v1.9.41.20220729S(1010945)的dex我已经反编译好了，生成动态码的so文件也可以脱壳，这些就不直接放GitHub了，如果需要可以找我。

目前学海的sign算法和之前相比也没有太大的变化，如果需要也请联系我。

**Comment by Hwenray** [comment]
> > > > 我也搞了个https://github.com/HWR20080716/UnhideXueHai/releases/tag/xuehai > > > > > > > > > 我没死之前收集了一大堆xhAPP > > > > > > nb > > 我也备份了一些，有非常远古的版本（标old的），还有两个测试版本的智通平台（标test的），现在应该还是可用的（禁用自动更新即可）： > > https://github.com/Jerry-Gren/Test-XH/releases/tag/v0.1.0 > > 这里面test_com.xh.zhitongyunstu_v3.74.5.20220624S和com.xuehai.launcher_v1.9.41.20220729S(1010945)的dex我已经反编译好了，生成动态码的so文件也可以脱壳，这些就不直接放GitHub了，如果需要可以找我。 > > 目前学海的sign算法和之前相比也没有太大的变化，如果需要也请联系我。 

要是之前遇到你该多好🤦早已毕业1 年

**Comment by butlanys** [comment]
> > > > > 我也搞了个https://github.com/HWR20080716/UnhideXueHai/releases/tag/xuehai > > > > > > > > > 我没死之前收集了一大堆xhAPP > > > > > > nb > > 我也备份了一些，有非常远古的版本（标old的），还有两个测试版本的智通平台（标test的），现在应该还是可用的（禁用自动更新即可）： > > https://github.com/Jerry-Gren/Test-XH/releases/tag/v0.1.0 > > 这里面test_com.xh.zhitongyunstu_v3.74.5.20220624S和com.xuehai.launcher_v1.9.41.20220729S(1010945)的dex我已经反编译好了，生成动态码的so文件也可以脱壳，这些就不直接放GitHub了，如果需要可以找我。 > > 目前学海的sign算法和之前相比也没有太大的变化，如果需要也请联系我。 
> 
> 要是之前遇到你该多好🤦早已毕业1 年
> 
> 
> 

这项目的坟头草都几米高了
